### ISSUE TITLE
Refit: Advanced vs simple

### ISSUE THREAD

**Issue by arichards2564** [taylor-lab/facets-preview#2]
Right now, when we run refits, we can modify the purity/hisens cvals, diplogR and the min.nhet. This is really nice but sometimes we might want to change other parameters (e.g. ndepth). It would be really nice to have 2 different options for refits: advanced and not. In the advanced, you could have all of the parameters that go into the doFacets call while the simple could just have the cvals and diplogR. That way we could change parameters when necessary but not have the complication of them all when we just wanted a simple default refit.

**Comment by cband** [comment]
Implemented this in v2.1.0
